### ISSUE TITLE
Android 12 Support

### ISSUE THREAD

**Issue by danherrera** [TapTrack/TCMPTappy-Android#3]
Hello,

I understand the current libraries are targeting API 29. Is there a plan to update to 31?

Starting with Android 12 (API 31), the Android system is requiring applications to define `PendingIntent`s as [mutable or immutable via a flag](https://developer.android.com/guide/components/intents-filters#DeclareMutabilityPendingIntent). Unfortunately, this results in a crash when a PendingIntent does not include this flag, which occurs when instantiating **UsbPermissionDelegate**.

```log
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at com.taptrack.tcmptappy2.usb.UsbPermissionDelegate.<init>(UsbPermissionDelegate.java:59)
```

**Comment by dshalaby** [comment]
Hello,

Thank you for raising this issue.  Yes we do plan on supporting Android 12.  I will look into adding this flag, however at the moment I can't recall if we're ever mutating this so I'll check and update this issue.  

Feel free to make a pull request too if you think you already have the fix 🙂

Thank you for choosing Tappy NFC readers.
